version: "3.9"  # optional since v1.27.0
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    container_name: mysql
    ports:
      - 8080:8080
    volumes:
      - /var/lib/docker/volumes/mySQL:/var/lib/mysql/
      - /var/lib/docker/volumes/mySQL_backup:/var/lib/mysql/backup

      


