version: "3.9"  # optional since v1.27.0
services:
  db:
    image: postgres:12.11-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - /var/lib/docker/volumes/postgres:/var/lib/postgresql/data/
      - /var/lib/docker/volumes/postgres_backup:/var/lib/postgresql/backup
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always
